#!/bin/bash

. /etc/inxifetch/inxifetch.conf

fgl="$(figlet -f $FontType $distro_name)"
echo -e "$colorF$fgl\e[0m"

inxi -c $color -Ib"$1"

fglr="$(figlet -f $FontType -Rl $distro_name)"
echo -e "$colorF$fglr\e[0m"


